# Site settings
title:  داده‌های گم‌شده
email: m.mosalman@gmail.com
description: نوشته‌های محمود مسلمان درباره داده، وب و مسائل پیرامونی!
baseurl: "" # the subpath of your site, e.g. /blog/
url:
twitter_username: mahmoudmy_
github_username:

# Build settings
markdown: kramdown

comments: true

gems:
  - jekyll-sitemap
